-- MySQL Script generated by MySQL Workbench
-- Sat Nov 21 13:19:04 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema laba7_1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema laba7_1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `laba7_1` DEFAULT CHARACTER SET utf8;
USE `laba7_1`;

-- -----------------------------------------------------
-- Table `laba7_1`.`electrical_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laba7_1`.`electrical_product`
(
    `electrical_product_id` BIGINT        NOT NULL AUTO_INCREMENT,
    `name`                  VARCHAR(45)   NOT NULL,
    `price`                 DECIMAL(7, 2) NOT NULL,
    `quantity`              INT           NOT NULL,
    `issue_year`            INT           NOT NULL,
    PRIMARY KEY (`electrical_product_id`)
)
    ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
