-- MySQL Script generated by MySQL Workbench
-- Mon Nov 23 08:36:30 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema laba7_2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema laba7_2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `laba7_2` DEFAULT CHARACTER SET utf8;
USE `laba7_2`;

-- -----------------------------------------------------
-- Table `laba7_2`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laba7_2`.`users`
(
    `users_id`   BIGINT      NOT NULL AUTO_INCREMENT,
    `name`       VARCHAR(30) NOT NULL,
    `surname`    VARCHAR(30) NOT NULL,
    `patronymic` VARCHAR(30) NOT NULL,
    `birthday`   BIGINT      NOT NULL,
    PRIMARY KEY (`users_id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laba7_2`.`letters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laba7_2`.`letters`
(
    `letters_id`           BIGINT       NOT NULL AUTO_INCREMENT,
    `theme`                VARCHAR(40)  NOT NULL,
    `text`                 VARCHAR(256) NOT NULL,
    `departure_date`       BIGINT       NOT NULL,
    `sender_users_id_fk`   BIGINT       NOT NULL,
    `receiver_users_id_fk` BIGINT       NOT NULL,
    PRIMARY KEY (`letters_id`),
    INDEX `fk_letters_users_idx` (`sender_users_id_fk` ASC) VISIBLE,
    INDEX `fk_letters_users1_idx` (`receiver_users_id_fk` ASC) VISIBLE,
    CONSTRAINT `fk_letters_users`
        FOREIGN KEY (`sender_users_id_fk`)
            REFERENCES `laba7_2`.`users` (`users_id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_letters_users1`
        FOREIGN KEY (`receiver_users_id_fk`)
            REFERENCES `laba7_2`.`users` (`users_id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
